# test dockerfile
FROM ubuntu:20.04

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y curl tar python3 openssh-server && \
    rm -rf /var/lib/apt/lists/*

# Download and extract Node Exporter
RUN curl -LO https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz && \
    tar -xvf node_exporter-1.1.2.linux-amd64.tar.gz && \
    mv node_exporter-1.1.2.linux-amd64/node_exporter /usr/local/bin && \
    rm -rf node_exporter-1.1.2.linux-amd64.tar.gz node_exporter-1.1.2.linux-amd64

# Configure SSH for root login
RUN mkdir /var/run/sshd && \
    echo 'root:root' | chpasswd
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config

# Expose the port for Node Exporter
EXPOSE 9100

# Run Node Exporter as the main process
CMD ["/usr/local/bin/node_exporter"]
