# test/Dockerfile

FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y python3 openssh-server && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /var/run/sshd && \
    echo 'root:root' | chpasswd

RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config


# exposes the port for Node Exporter
EXPOSE 9100




CMD ["/usr/sbin/sshd", "-D"]
