# ansible dockerfile

FROM python:3.8-slim

RUN apt-get update && \
    apt-get install -y ssh ansible sshpass && \
    rm -rf /var/lib/apt/lists/*

ENV ANSIBLE_HOST_KEY_CHECKING=False    

WORKDIR /ansible
CMD ["tail", "-f", "/dev/null"]
