- name: Configure test host
  hosts: test
  become: yes

  tasks:
  - name: Install necessary dependencies
    apt:
      name:
      - python3-pip
      state: present
      update_cache: yes

  - name: Download Prometheus
    get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.31.1/prometheus-2.31.1.linux-amd64.tar.gz
      dest: /tmp

  - name: Extract Prometheus archive
    unarchive:
      src: /tmp/prometheus-2.31.1.linux-amd64.tar.gz
      dest: /opt
      remote_src: yes
      creates: /opt/prometheus-2.31.1.linux-amd64

  - name: Create symbolic link for Prometheus
    file:
      src: /opt/prometheus-2.31.1.linux-amd64
      dest: /opt/prometheus
      state: link

  - name: Create Prometheus service file
    copy:
      dest: /etc/systemd/system/prometheus.service
      content: |
        [Unit]
        Description=Prometheus Server
